### ISSUE TITLE
Call to a member function toArray() on false

### ISSUE THREAD

**Issue by dreigningking** [alajusticia/laravel-logins#1]
`..\vendor\alajusticia\laravel-logins\src\RequestContext.php :

'device' => $this->parser()->getDevice(),
'application' => $this->tokenName(),
'platform' => $this->parser()->getPlatform(),
'browser' => $this->parser()->getBrowser(),
'ip' => $this->ipAddress(),
'location' => $this->location()?->toArray(),`

Call to a member function toArray() on false at $this->location()?->toArray()

**Comment by alajusticia** [comment]
Thank you for reporting this issue, it is now fixed in [v.1.2.3 release](https://github.com/alajusticia/laravel-logins/releases/tag/v1.2.3).
