### ISSUE TITLE
Add the passport option

### ISSUE THREAD

**Issue by omarsenusi** [alajusticia/laravel-logins#2]
There is no passport. It would be great to add it. Why didn't you add it?!

**Comment by alajusticia** [comment]
Passport is not supported because I don't use it. I used to support it in another package (not maintained anymore), but since there were some breaking changes in new versions of Passport. I don't have plans to support it in the near future.

**Comment by zhiyong-ft** [comment]
How difficult/easy is it to add support for Passport? I am thinking of giving it a try, but not sure if I'm up to it.

**Comment by alajusticia** [comment]
That would require several modifications. Right now, what comes to mind is:

- Add an attribute on our Login model with a relation for the Passport Token model (and a migration to add a `passport_token_id` column in the logins table)
- Add a method in the LoginFactory to handle login creation from a Passport token
- Add event listeners for Passport events (https://laravel.com/docs/12.x/passport#events) to call the new factory method when a new Passport token is issued, and delete login when Passport tokens are revoked
- Create new helpers to manage Passport tokens and update the HasLogins trait, LoginsScope macros and ManagesLogins trait to use these helpers

**Comment by zhiyong-ft** [comment]
> That would require several modifications. Right now, what comes to mind is:
> 
>     * Add an attribute on our Login model with a relation for the Passport Token model (and a migration to add a `passport_token_id` column in the logins table)
> 
>     * Add a method in the LoginFactory to handle login creation from a Passport token
> 
>     * Add event listeners for Passport events (https://laravel.com/docs/12.x/passport#events) to call the new factory method when a new Passport token is issued, and delete login when Passport tokens are revoked
> 
>     * Create new helpers to manage Passport tokens and update the HasLogins trait, LoginsScope macros and ManagesLogins trait to use these helpers

Thanks for the pointers. Any idea on how to deal with switching between Sanctum and Passport? I don't think anyone will use Sanctum and Passport in the same app, so some sort of tag in `config/logins.php` would work.
