### ISSUE TITLE
Issues with sanctum token authentication

### ISSUE THREAD

**Issue by thomasakarlsen** [alajusticia/laravel-logins#4]
I am having an issue with sanctum token authentication and this package. 
In my controller I was trying to get the `current_login` from the user, but it was always null. 
The controller is behind the `auth:sanctum` middleware, and the user is available in the controller.

Digging through the chain of events it seems like the issue lies with `Auth::user()` (in CurrentLogin.php) being null when the `TokenAuthenticated` event is being issued by sanctum.

**Comment by thomasakarlsen** [comment]
In my efforts to find a workaround for this I decided to add a middleware to perform early authentication using `Auth::setUser(Auth::guard('sanctum')->user());`. The added benefit of this route is having the user available on routes that not behind the `auth:sanctum` middleware too.
This workaround however gave me a different issue, which I belive to just be a typo in `CurrentLogin.php`.
Instead of being `$this->logins()` I belive this line should be `Auth::user()->logins()`, like the rest of the file.
https://github.com/alajusticia/laravel-logins/blob/dd7b6dcffbdd7fc130629be421014e895fdccdc0/src/CurrentLogin.php#L29

Modifying `CurrentLogin.php` gives me a fully working setup where I have the user available early, even in middlewares, and with the correct login session available on `current_login`.

**Comment by alajusticia** [comment]
Thanks for reporting this issue!
The current login is now based on the authenticatable model from the Authenticated and TokenAuthenticated events.

Fixed in [v1.2.5](https://github.com/alajusticia/laravel-logins/releases/tag/v1.2.5)
