### ISSUE TITLE
Race condition with middleware, remember me tokens & session id tracking

### ISSUE THREAD

**Issue by thomasakarlsen** [alajusticia/laravel-logins#6]
**Background**:
In my application I have extended the `Login` model to add an extra field which keeps track of their currently selected organization.
To enforce that a user always has a selected organization I have added a middleware to all routes (except for login and registration) which uses their `current_login` to get the active organization for that login. The middleware itself is added via groups in the web routes file and is nested beneath the `auth` middleware. When you log in to the application the remember me option is enforced.

**Issue**:
During testing I realized that after a session expires and for your first request, when you are "signed in again" by the remember me token, the `current_login` attribute of the user is not set in time for when the middleware is run. On the next request the `current_login` is available as normal.

From my investigating the issue seems to stem from the logins `session_id` being updated too late when the user is signed in by a remember me token. It seems to me that during a "remember me token" login we are relying on the `Authenticated` event from Laravel to trigger the `checkSessionId` function which then updates the `session_id` of the current login with the new `session_id`. This event seems to be fired AFTER middlewares are run.

 Trying to find a solution I looked at the `Login` event that is also being listened for. In my cases it seems like the session id is always available when this event has been triggered. For my temporary fix I added another case to the if in the handler:
 
 ```php
public function handleSuccessfulLogin(\Illuminate\Auth\Events\Login $event): void
{
    if (! Auth::viaRemember() && Logins::tracked($event->user)) {
        Logins::trackLoginFromSession(session()->getId(), $event->guard, $event->user, $event->remember);
    } else if (Auth::viaRemember() && Logins::tracked($event->user)) {
        Logins::checkSessionId($event->user);
    }
}
 ```
 
 This seems to fix the issue for me and the current login is available in the middleware as expected. 
 
 While this works, I am unsure if this is a good solution or if it introduces vulnerabilities (i.e session hijacking)

**Comment by alajusticia** [comment]
Thanks for reporting this issue!

I was able to reproduce it and made a fix in [v1.2.6](https://github.com/alajusticia/laravel-logins/releases/tag/v1.2.6) following your solution (except that I used a simple else statement because we already check if logins are tracked for the user in the checkSessionId method).
